services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pages_db
    ports:
      - 5432:5432

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
